#!/usr/bin/env python3
"""
Generate cpu16tab.h, the CPU16 opcode table, from cpu16_ops.json.

cpu16_ops.json is Table 6-36 (Instruction Set Summary) of the CPU16
Reference Manual (CPU16RM/AD), parsed: one row per mnemonic and
addressing mode with its opcode, operand bytes, cycles and CCR effect
(S MV H EV N Z V C: '-' unaffected, '*' computed, '0'/'1' forced, 'U'
undefined).  Encodings were cross-checked against the opcode table of the
Real-Time Systems hc16 GNU assembler (all rows agree, the assembler lacks
only BRCLR/BRSET with 8-bit offsets); the operand layouts of the bit
instructions follow the glossary pages, which list operands the summary
leaves out (BCLRW/BSETW mask word, BRCLR/BRSET 16-bit branch offset).

    python3 tools/cpu16tab.py > cpu16tab.h
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))

MODES = ["INH", "IMM8", "IMM16", "IND8", "IND16", "EXT", "EIDX", "IND20",
         "EXT20", "REL8", "REL16", "IXP_EXT", "EXT_IXP", "EXT_EXT"]

OPSZ = {'—': 0, 'ff': 1, 'ii': 1, 'gggg': 2, 'hh ll': 2, 'jj kk': 2, 'jjkk': 2,
        'hhll': 2, 'rrrr': 2, 'rr': 1, 'mm gggg': 3, 'mm ff': 2, 'mm ff rr': 3,
        'zg gggg': 3, 'mm hh ll': 3, 'ff hh ll': 3, 'zb hh ll': 3, 'xoyo': 1,
        'hh ll hh ll': 4}

FLAGBIT = [15, 14, 13, 12, 11, 10, 9, 8]	# S MV H EV N Z V C


def mode_of(m):
    """('IND16', reg) from the table's mode text"""
    m = m.replace(' ', '')
    reg = 0
    mm = re.match(r'^(IND8|IND16|IND20|E),([XYZ])$', m)
    if mm:
        reg = "XYZ".index(mm.group(2))
        base = {"IND8": "IND8", "IND16": "IND16", "IND20": "IND20", "E": "EIDX"}[mm.group(1)]
        return base, reg
    m = {"IXPtoEXT": "IXP_EXT", "EXTtoIXP": "EXT_IXP", "EXTtoEXT": "EXT_EXT"}.get(m, m)
    assert m in MODES, m
    return m, reg


def length(x, mode):
    n = len(x['op']) // 2 + OPSZ[x['opnd']]
    if x['mn'] in ('BRCLR', 'BRSET') and mode != 'IND8':
        n += 2			# rrrr
    if x['mn'] in ('BCLRW', 'BSETW'):
        n += 2			# mmmm
    assert n % 2 == 0, x
    return n


def cycles(c):
    """(cycles, alternate) -- alternate: not taken for branches, the
    per-register/iteration count for PSHM/PULM/RMAC, S=0 for LPSTOP"""
    c = c.replace(' ', '')
    if c == '—':
        return 0, 0
    if c == '4+2N':
        return 4, 2
    if c == '4+2N1':		# 4 + 2(N+1)
        return 6, 2
    if c == '6+12':
        return 6, 12
    a = [int(v) for v in c.split(',')]
    return a[0], a[1] if len(a) > 1 else a[0]


def main():
    rows = json.load(open(os.path.join(HERE, "cpu16_ops.json")))
    names = sorted(set(r['mn'] for r in rows))
    tab = [[None] * 256 for _ in range(4)]
    pages = {0: 0, 0x17: 1, 0x27: 2, 0x37: 3}
    for x in rows:
        op = int(x['op'], 16)
        if len(x['op']) == 4:
            page, code = pages[op >> 8], op & 0xFF
        else:
            page, code = 0, op
        mode, reg = mode_of(x['mode'])
        c1, c2 = cycles(x['cyc'])
        fmask = fset = fclr = 0
        for ch, bit in zip(x['flags'], FLAGBIT):
            if ch in '*U':
                fmask |= 1 << (bit - 8)
            elif ch == '0':
                fclr |= 1 << (bit - 8)
            elif ch == '1':
                fset |= 1 << (bit - 8)
        assert tab[page][code] is None, x
        tab[page][code] = (names.index(x['mn']), mode, reg, length(x, mode), c1, c2,
                           fmask, fset, fclr, x['mn'])
    print("/* generated by tools/cpu16tab.py from tools/cpu16_ops.json; do not edit */")
    print("#ifndef CPU16TAB_H\n#define CPU16TAB_H\n")
    print("enum cpu16_mn {\n\tMN_ILL = 0,")
    for n in names:
        print("\tMN_%s," % n)
    print("\tMN_COUNT\n};\n")
    print("enum cpu16_mode {\n" + "".join("\tM_%s,\n" % m for m in MODES) + "};\n")
    print("/* page: 0 = one-byte opcodes, 1 = 17xx, 2 = 27xx, 3 = 37xx.  len in bytes;")
    print(" * cyc the summary's count (taken), alt the second count (see cpu16tab.py);")
    print(" * fmask/fset/fclr are CCR[15:8] bits the instruction computes/sets/clears */")
    print("struct cpu16_op {\n\tuint16_t mn;\n\tuint8_t mode, reg, len, cyc, alt, fmask, fset, fclr;\n};\n")
    print("static const char *const cpu16_names[MN_COUNT] = {\n\t\"???\",")
    for n in names:
        print("\t\"%s\"," % n)
    print("};\n")
    print("static const struct cpu16_op cpu16_ops[4][256] = {")
    for p in range(4):
        print("\t{")
        for code in range(256):
            e = tab[p][code]
            if e is None:
                continue
            mn, mode, reg, ln, c1, c2, fm, fs, fc, name = e
            print("\t\t[0x%02X] = { MN_%s, M_%s, %d, %d, %d, %d, 0x%02X, 0x%02X, 0x%02X }," %
                  (code, name, mode, reg, ln, c1, c2, fm, fs, fc))
        print("\t},")
    print("};\n\n#endif")


if __name__ == "__main__":
    main()
