#!/usr/bin/env python3
"""
How tools/cpu16_ops.json was made (kept for provenance; the JSON is the
input of cpu16tab.py and is not regenerated by the build).

    pdftotext -layout CPU16RM.pdf CPU16RM.txt       # the CPU16 Reference Manual
    python3 tools/cpu16_parse.py CPU16RM.txt > tools/cpu16_ops.json

It takes Table 6-36 (Instruction Set Summary) from the text, joins the
continuation rows to their mnemonic, strips footnote digits from
mnemonics, and adds the rows the text extraction split (MOVB/MOVW EXT to
EXT, PULM).  The CCR columns become an 8-character string over
S MV H EV N Z V C ('-' unaffected, '*' computed, '0'/'1', 'U').
"""
import json
import re
import sys

MODE = (r'(INH|IMM8|IMM16|IND8, ?[XYZ]|IND16, ?[XYZ]|IND20, ?[XYZ]|EXT20|EXT|E, ?[XYZ]'
        r'|REL8|REL16|IXP to EXT|EXT to IXP|EXT to EXT|[A-Z0-9, ]+ to [A-Z0-9, ]+)')
ROW = re.compile(r'(?:^|\s)' + MODE + r'\s+([0-9A-F]{2}(?:[0-9A-F]{2})?)\s+(.*?)\s+'
                 r'(\d+(?:\s*[+,]\s*\d+)?(?:\s*[+,]\s*\d+)?|—)(\s.*)?$')


def clean(lines):
    out = []
    for line in lines:
        s = line.strip()
        if re.search(r'Freescale Semiconductor|For More Information|Go to: www.freescale'
                     r'|^MOTOROLA\b|^CPU16\s+(MOTOROLA|REFERENCE)|REFERENCE MANUAL', s):
            continue
        out.append(re.sub(r'\s{2,}', '  ', s))
    return out


def main(path):
    text = clean(open(path, encoding="utf8").read().split("\n"))
    a = next(i for i, l in enumerate(text) if l.startswith("6.4 Instruction Set Summary")
             and i > 1000)
    b = next(i for i, l in enumerate(text) if i > a and l.startswith("SECTION 7 INSTRUCTION PROCESS"))
    rows, mn = [], None
    for s in text[a:b]:
        s = s.replace("ORP 1  ", "ORP  ")
        s = re.sub(r"^PULM1  (.*)4\+2\(N\+1\)", r"PULM  \g<1>4+2N1", s)
        if not s or s.startswith(("Table", "Mnemonic", "Mode")):
            continue
        m0 = re.match(r'^([A-Z][A-Z0-9]{1,6})\s{2}', s)
        m = ROW.search(s)
        if m0 and not re.match(r'^(INH|IMM8|IMM16|IND8|IND16|IND20|EXT|EXT20|REL8|REL16|IXP|E)$',
                               m0.group(1)):
            mn = m0.group(1)
        if m:
            rows.append(dict(mn=mn, mode=m.group(1).replace(", ", ","), op=m.group(2),
                             opnd=m.group(3).strip(), cyc=m.group(4),
                             rest=(m.group(5) or "").strip()))
    flags = {}
    for x in rows:
        if x["mn"][-1].isdigit():
            x["mn"] = x["mn"][:-1]
        x["mode"] = re.sub(r'^.*IXP to EXT.*$', 'IXP to EXT', x["mode"]).strip()
        if x["mode"].startswith("B to XK"):
            x["mode"] = "INH"
        toks = [t for t in x["rest"].split() if t in ("—", "∆", "0", "1", "U")]
        if len(toks) >= 8:
            flags[x["mn"]] = "".join({"—": "-", "∆": "*"}.get(t, t) for t in toks[:8])
    rows.append(dict(mn="MOVB", mode="EXT to EXT", op="37FE", opnd="hh ll hh ll", cyc="10"))
    rows.append(dict(mn="MOVW", mode="EXT to EXT", op="37FF", opnd="hh ll hh ll", cyc="10"))
    if not any(x["mn"] == "PULM" for x in rows):
        rows.append(dict(mn="PULM", mode="IMM8", op="35", opnd="ii", cyc="4+2N1"))
        flags["PULM"] = "********"
    out = [dict(mn=x["mn"], mode=x["mode"], op=x["op"], opnd=x["opnd"],
                cyc=x["cyc"].replace(" ", ""), flags=flags.get(x["mn"], "????????"))
           for x in rows]
    json.dump(out, sys.stdout, indent=0)


if __name__ == "__main__":
    main(sys.argv[1])
